# Generated by Django 4.1 on 2022-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='ссылка', max_length=100, null=True, verbose_name='Ссылка на GitHub проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='other_link',
            field=models.CharField(default='ссылка', max_length=100, null=True, verbose_name='Ссылка на сторонний ресурс'),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='achievements',
            field=models.CharField(max_length=100, verbose_name='Достижение в проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название проекта'),
        ),
    ]
