# Generated by Django 4.1 on 2022-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_accomplishment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=100, verbose_name='Ссылка на GitHub проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Ссылка на сторонний ресурс'),
        ),
    ]
