# Generated by Django 4.1 on 2022-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_project_github_link_alter_project_other_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на сторонний ресурс'),
        ),
    ]
