# Generated by Django 4.1 on 2022-08-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_project_other_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'Group',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на сторонний ресурс'),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/skills/', verbose_name='Изображение к навыку')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.group')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'db_table': 'Technology',
            },
        ),
    ]
